title: Kit's Blog - Rival Rockets
description: The ramblings of self-declared winners
email: kit@rivalrockets.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rivalrockets.com"
twitter_username: rivalrockets
github_username:  rivalrockets

disqus_shortname: rivalrockets

google_analytics_ua: UA-7052368-1

# Build settings
markdown: kramdown
